### ISSUE TITLE
¿Hay versión "stable"?

### ISSUE THREAD

**Issue by drg809** [compropago/compropago-php#2]
Al instalar la librería mediante composer me invoca "InvalidArgumentException" diciendome que no encuentra el paquete en una versión para mi "Minimum Stability". Según he encontrado en la docu de composer, se debe  a que mi configuración exige una versión estable para instalar las librerías. Mi pregunta es que ¿si aún se encuentra en desarrollo o es un problema de mi sistema?. Muchas gracias.

**Comment by waldix** [comment]
Hola me presento soy Oswaldo López encargado del area TI en ComproPago y si
todavía estamos en modo desarrollo, el día Lunes ya tendríamos una versión
estable, si gustas proporcionarme algún contacto para ponernos en contacto
contigo y solucionar tu problema.

Saludos.

**Comment by drg809** [comment]
Muchas gracias Oswaldo por tu respuesta tan temprana, les felicito por su API y también por su cercana versión estable, la cual instalaré. De momento ya lo he solucionado, solo era decirle que instalara la versión dev. Mi nombre es Daniel y llevo unos días informándome sobre su servicio para implentarlo en mi app con AngularJS. Puedes escribirme a drg809 arroba gmail punto com.
