### ISSUE TITLE
 Class 'Compropago\Client' not found

### ISSUE THREAD

**Issue by gustavomanolo** [compropago/compropago-php#3]
Hola, instalé la librería vía composer pero cuando intento crear la instancia de la clase Client me marca el siguiente error:

 Class 'Compropago\Client' not found

¿Alguna solución?
Gracias.

**Comment by rolandolucio** [comment]
saludos, pareciera que no se esta incluyendo los archivos,  podrías ejecutar lo siguiente:  composer dumpautoload -o

**Comment by gustavomanolo** [comment]
Muchas gracias, con eso quedó solucionado.
