### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gesquivelob** [compropago/compropago-php#31]
Existen errores en su URL, consulte la documentación de los estandares de webhooks aquí 
Response: el payload esparado es diferente.

Fatal error:  Class 'CompropagoSdk\Factory\Factory' not found in /home/qubomx/public_html/procesos/ComproPago_IPN.php on line 16

**Comment by danteay** [comment]
@gesquivelob El error que te esta marcando no es de parseo en las peticiones, si no mas bien esta marcando que no existe la clase Factory. esto puede ser porque no estas cargando correctamente el SDK en tu archivo **ComproPago_IPN.php**. Como generaste tu instalación, vía composer, o directo de git?

**Comment by gesquivelob** [comment]
Gracias por responder! me di cuenta de inmediato que ese era el problema. Ahora tengo otra pregunta, podría orientarme como transformar la información enviada por comproPago a mi servidor de Json a otro formato? para poder usarlo en PHP. Disculpe pues no tengo experiencia en este tipo de acciones.

**Comment by danteay** [comment]
@gesquivelob La clase Factory del SDK de ComproPago tiene implementado todos los objetos PHP necesarios para transformar uns string de JSON a culquier objeto valido en los esquemas de ComproPago. Especificamente en la cuestion del webhook puedes generar algo como esto al momento de recibir la petición desde el servidor de compropago.

```php
require __DIR__ . '/path/to/vendor/autoload.php';

use CompropagoSdk\Factory\Factory;

$response = file_get_cotents('php://input');

$orderInfo = Factory::getInstanceOf('CpOrderInfo', $response);

# Maneja tu codigo aqui
```

Puedes revisar la documentacion del SDK en esta pagina [http://demo.compropago.com/sdk/php](http://demo.compropago.com/sdk/php)

**Comment by gesquivelob** [comment]
Con eso podré usar las respuestas como $orderInfo['id'] ??

**Comment by gesquivelob** [comment]
Éste es mi código: 

`
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

include dirname(dirname(__FILE__))."/connectdb.php";

require_once 'vendor/autoload.php';

use \Mailjet\Resources;

require_once 'CompropagoSdk/Client.php';

use CompropagoSdk\Client;
Client::register_autoload();

use CompropagoSdk\Factory\Factory;

$request = @file_get_contents('php://input');
header('Content-Type: application/json');

if(!$resp_webhook = Factory::getInstanceOf('CpOrderInfo', $request)){
    echo json_encode([
      "status" => "error",
      "message" => "invalid request",
      "short_id" => null,
      "reference" => null
    ]);
}

$publickey     = "XXX";
$privatekey    = "XXX";
$live          = false; // si es modo pruebas cambiar por 'false'

try{
    $client = new Client($publickey, $privatekey, $live );

    if($resp_webhook->id == "ch_00000-000-0000-000000"){
        echo json_encode([
          "status" => "success",
          "message" => "test success",
          "short_id" => $resp_webhook->short_id,
          "reference" => null
        ]);
    }

    $response = $client->api->verifyOrder($resp_webhook->id);

    switch ($response->type){
        case 'charge.success':
            // TODO: Actions on success payment
			
			if($resp_webhook = Factory::getInstanceOf('CpOrderInfo', $request)){
			
			$transaction_id = htmlspecialchars(addslashes(stripslashes(strip_tags(trim($request['id']))))); //ID de Transaccion
			$amount = htmlspecialchars(addslashes(stripslashes(strip_tags(trim($request['amount']))))); //Monto
			$order_id = htmlspecialchars(addslashes(stripslashes(strip_tags(trim($request['order_id']))))); //ID del Producto
			$nombre = htmlspecialchars(addslashes(stripslashes(strip_tags(trim($request['customer_name']))))); //Nombre del Cliente
			$customer_email = htmlspecialchars(addslashes(stripslashes(strip_tags(trim($request['customer_email']))))); //Email del Cliente
			}
			
			$fecha = date('Y-m-d H:i:s');
			$ip = $_SERVER['REMOTE_ADDR'];
			
			$compra = explode("R", $order_id);
			$tipo = $compra[0]; // tipo
			$referido = $compra[1]; // referido
			
			
			//El pago ha sido recibido y completado con éxito, entonces aqui colocamos el código que deseamos.
				   if (!$mysqli->query("INSERT INTO `aportaciones` (`id`, `referido`, `order_id`, `cantidad`, `trans`, `nombre`, `cuenta`, `metodo`, `fecha`, `ip`, `status`) VALUES 
					(NULL, 
					'".$referido."', 
					'".$tipo."', 
					'".$amount."', 
					'".$transaction_id."', 
					'".$nombre."', 
					'".$customer_email."', 
					'ComproPago', 
					'".$fecha."', 
					'".$ip."', 
					'confirmado');")) {
				echo "Falló la Insersión de Datos: (" . $mysqli->errno . ") " . $mysqli->error;
			} else {
				
				
			$apikey = 'XXX';
			$apisecret = 'XXX';

			// use your saved credentials
			$mj = new \Mailjet\Client($apikey, $apisecret);

			$orig = array("[nombre]", "[cantidad]", "[cuenta]", "[trans]");
			$newva   = array("$first_name", "$amount", "$customer_email", "$transaction_id");

			$body = [
				'FromEmail' => "soporte@qubo.mx",
				'FromName' => "Qubo",
				'Subject' => "Pago Recibido",
				'Html-part' => str_replace($orig, $newva, file_get_contents('../procesos/content/fondos/paypal.html')),
				'Recipients' => [
					[
						'Email' => "{$customer_email}"
					]
				]
			];
			$response = $mj->post(Resources::$Email, ['body' => $body]);
				
				
			include dirname(dirname(__FILE__))."../closedb.php";

			 }
			
			
            break;
        case 'charge.pending':
            // TODO: Actions on pending payment
            break;
        case 'charge.expired':
            // TODO: Actions on expired payment
            break;
        default:
            echo json_encode([
              "status" => "error",
              "message" => "invalid request type",
              "short_id" => $response->short_id,
              "reference" => null
            ]);
    }

    echo json_encode([
      "status" => "success",
      "message" => "OK",
      "short_id" => $response->short_id,
      "reference" => 'internal-1234'
    ]);
}catch (Exception $e) {
    echo json_encode([
      "status" => "error",
      "message" => $e->getMessage(),
      "short_id" => $resp_webhook->short_id,
      "reference" => null
    ]);
}
`

**Comment by danteay** [comment]
Con esa implemetación ya puedes acceder a la información pero no como un arreglo como lo mencionas, si no mas bien como atributos de un objeto. Lo que tu mensionabas como `$orderInfo['id']` mas bien lo tendrias que acceder como `$orderInfo->id` y asi con todos los demas campos: puedes revisar los modelos y sus parametros dentro del codigo del SDK en la carpeta **Factory\Models**

**Comment by gesquivelob** [comment]
Ya logré hacer que esto trabaje correctamente:

```
if($resp_webhook = Factory::getInstanceOf('CpOrderInfo', $request)){
			$transaction_id = $resp_webhook->id; //ID de Transaccion
			$amount = $resp_webhook->amount; //Monto
			$order_id = $resp_webhook->order_id; //ID del Producto
			}
```

Pero esto otro no me trae ningún resultado:

```
if($cliente = Factory::getInstanceOf('Customer', $request)){
			$nombre = $cliente->customer_name; //Nombre del Cliente
			$customer_email = $cliente->customer_email; //Email del Cliente
			}
```

**Comment by danteay** [comment]
Es porque ya viene embedido dentro del primer objeto si quieres acceder a la información del cliente serial el siguiente:

```php
$customer = $resp_request->customer;
$orderInfo = $resp_request_order_info;

$nombre = $customer->client_name;
$email = $customer->client_email;

$orderId = $orderInfo->order_id;
$orderName = $orderInfo->order_name;
$orderPrice = $orderInfo->amount;
```

Este es el esquema de el objeto **CpOrderInfo** [https://compropago.com/documentacion/api/verificar-cargo](https://compropago.com/documentacion/api/verificar-cargo)

**Comment by gesquivelob** [comment]
Al fin comprendido y resuelto :)

```
$transaction_id = $resp_webhook->id; //ID de Transaccion
$amount = $resp_webhook->amount; //Monto
			
$customer = $resp_webhook->customer;
$orderInfo = $resp_webhook->order_info;

$nombre = $customer->customer_name;
$customer_email = $customer->customer_email;

$order_id = $orderInfo->order_id;	
```

**Comment by gesquivelob** [comment]
Es posible especificar un Webhook específico en un botón de pago?

**Comment by danteay** [comment]
No, los webhooks que registres no distinguirán entre los pagos, así que
todos los eventos de todos los pagos llegarán a todos tus webhooks

**Comment by gesquivelob** [comment]
Gracias por ayudar! cierro el tema :)
